preset: laravel
enabled:
    - concat_with_spaces
    - align_equals
disabled:
    - trailing_comma_in_multiline_array
    - concat_without_spaces
    - unalign_equals
    - not_operator_with_successor_space
    - no_blank_lines_after_class_opening